language: node_js

before_script:
  - mysql -e 'create database firenze;'

node_js:
  - 'stable'
  - '0.12'

script: "npm run test && npm run coverage && npm run dist && npm run karma"

notifications:
  email: false
